### ISSUE TITLE
Create Contacts Activity

### ISSUE THREAD

**Issue by gabowser** [MarschOSX/Responder#36]
Create contacts page that has all existing contacts

**Comment by MarschOSX** [comment]
We currently have a scrollable list of LOCAL contacts. I simply created them in a .xml file and used it to get a start. Each contact can also be pressed to go into a sub-activity for that specific contact. We need to still access contacts on the device, have an add contact button that updates the list, and have information stored in the Single contact screen based on the name. For DB access per contact, maybe pass the name from ContactList->SingleContact, and that name be what we call the info from the DB?

**Comment by MarschOSX** [comment]
I have also raised the API from 19->21
