### ISSUE TITLE
Create Settings Activity

### ISSUE THREAD

**Issue by gabowser** [MarschOSX/Responder#37]
Store all settings in an activity to be changed by the user (instead of merged into General Reply)

**Comment by MarschOSX** [comment]
Why is the settings activity so different from the rest? did you get this from a website? I can reformat to a clean slate activity but I don't want to delete your work there. We will talk when together

**Comment by MarschOSX** [comment]
Move General Reply items into here, or maybe just change General Reply to settings! Might be easier

**Comment by gabowser** [comment]
Already working on this, I have it on a separate branch until complete. I
must have forgotten to open the issue

**Comment by MarschOSX** [comment]
You probably know, but just documenting it. The set delay doesn't work, and do we need to change the replyAll() to defualt? Plus once this is all fixed we can get rid of the GeneralResponse UI

**Comment by MarschOSX** [comment]
Just had a new idea. What if we leave the General Rely, but rename it to All Reply? Create a new toggle on the home screen, and this would override all contacts/groups (including default) as a universal message to all??? That way if you just want to tell anyone in your contacts who texts you a universal message, you dont need to go contact-by-contact to set it all?

**Comment by gabowser** [comment]
I fixed the problem with the set delay (will push the change soon. Also, in the Single Group, you don't need to check the inheritance value, the database does that for you. So if inheritance is true, the database loads the group response and permissions into the contact info automatically.

For example:

Group:  (testGroup, "generic group response", true (location), true (activity))
Contact: (+111111111, "testSubject", "testGroup", "my response", false (location), false (activity), true)

So since the last value (inheritance) is true, when you call getContactInfo(+111111111) you get: 
(+111111111, "testSubject", "testGroup", "generic group response", true (location), true (activity)), true)
